# docker-compose.yml for TooSensitive WordPress
# This is for local development reference - Railway will handle services separately
version: '3.8'

services:
  wordpress:
    build: .
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: toosensitive_wp
      WORDPRESS_TABLE_PREFIX: ts_
      WORDPRESS_DEBUG: 'true'
    volumes:
      - wordpress_data:/var/www/html/wp-content/uploads
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: toosensitive_wp
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  wordpress_data:
  mysql_data: